#ifndef HTTP_CONFIG_H_
#define HTTP_CONFIG_H_

#define HTTP_SERVER_MAX_CONNECTIONS 3
#define WEBSOCKET_SERVER_MAX_CONNECTIONS 3
#define HTTP_LINE_LEN 64

#define HTTP_SERVER_TIMEOUT_SECS  4
#define HTTP_SERVER_TIMEOUT_USECS (500 * 1000)

#define HTTP_WWW_DIR "www"

#endif
